apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: AZURE
    config:
      storage_account: MYSTORAGEACCOUNT
      storage_account_key: STORAGEACCOUNTKEY
      container: acmobservability
      endpoint: blob.core.windows.net
      max_retries: 0
