apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: test-acm-observability
      endpoint: bucket.MYBUCKET.s3.eu-west-1.vpce.amazonaws.com
      insecure: true
      access_key: ACCESSKEY
      secret_key: SECRETKEY
